#!/usr/bin/env bash

# Deploy portable user configuration using GNU Stow.
#
# Stow creates symlinks from ~/.config back into this repository, so editing
# either location edits the same tracked file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if ! command -v stow >/dev/null 2>&1; then
    echo "error: GNU Stow is not installed. Run ./install/base.sh first." >&2
    exit 1
fi

cd "$ROOT/dotfiles"

# --restow updates existing Stow-managed links without duplicating them.
stow --restow --target="$HOME" niri fish kitty

# These are generated by Noctalia's built-in templates. Empty placeholders let
# Niri and Kitty start before Noctalia has rendered the first wallpaper palette.
mkdir -p "$HOME/.config/niri" "$HOME/.config/kitty/themes"
touch "$HOME/.config/niri/noctalia.kdl"
touch "$HOME/.config/kitty/themes/noctalia.conf"

echo "Portable dotfiles deployed."
echo "Next: ./install/host.sh acer-laptop"
